export const ORCHESTRATION_PATTERNS = {
  token: {
    label: 'Token-to-Twin Planning',
    short: 'Token-to-Twin',
    outcomeKind: 'Plan',
    summary: 'Convert business or workload intent into a DSX-aware AI Factory system-of-systems plan.',
    intentLabel: '250MW AI Factory intent',
    context: ['RFP / OPR', 'DSX baseline', 'site constraints', 'previous AI Factory lessons'],
    outcomeTitle: 'DSX-aware AI Factory decision package',
    outcome:
      'Recommended DSX baseline, required simulations, OpenUSD/SimReady asset needs, cross-factory lessons, risks, deviations and next governed actions.',
    best: 'Strategic architecture and portfolio-level AI Factory planning.',
    agents: [
      {
        name: 'DSX Rules Agent',
        role: 'Checks DSX baseline, operating envelope and deviation needs.',
        input: 'Intent, site constraints, DSX reference content.',
        output: 'Baseline selection, constraints and deviation candidates.',
        nvidia: 'Omniverse DSX Blueprint / DSX reference corpus via NeMo Retriever.',
        evidence: 'Rule references, source snippets and deviation log.',
      },
      {
        name: 'Requirements Agent',
        role: 'Turns business intent into structured requirements and assumptions.',
        input: 'Natural-language intent, RFP fragments and business objectives.',
        output: 'Requirement objects, assumptions and missing inputs.',
        nvidia: 'NIM-hosted LLM with structured JSON output.',
        evidence: 'Prompt-to-process contract and validated schema.',
      },
      {
        name: 'Fleet Lessons Agent',
        role: 'Compares with previous AI Factory baselines and known lessons.',
        input: 'Previous AI Factory records and lessons learned.',
        output: 'Reusable patterns, risks and precedent evidence.',
        nvidia: 'NeMo Retriever + cuVS vector search over lessons learned.',
        evidence: 'Matched prior cases and confidence notes.',
      },
      {
        name: 'Power / Cooling Agent',
        role: 'Identifies power, cooling and water constraints to validate.',
        input: 'Site constraints, rack density, cooling targets and workload profile.',
        output: 'Candidate power/cooling checks and simulation needs.',
        nvidia: 'PhysicsNeMo candidate + simulation result index.',
        evidence: 'Required model inputs and no-invented-result gate.',
      },
      {
        name: 'Compute / Network Agent',
        role: 'Maps workload intent to racks, pods, topology and interconnect needs.',
        input: 'Token demand, expansion objectives and DSX system model.',
        output: 'Compute/network impact map and interconnect assumptions.',
        nvidia: 'DSX Blueprint + OpenUSD/SimReady context.',
        evidence: 'Topology assumptions and traceability to DSX baseline.',
      },
      {
        name: 'Evidence Agent',
        role: 'Assembles the traceable decision package.',
        input: 'Outputs from all specialized agents.',
        output: 'Evidence-backed recommendation package.',
        nvidia: 'NIM summarization + NeMo Retriever reranking.',
        evidence: 'Audit trail and traceability matrix.',
      },
    ],
    tools: ['Omniverse DSX Blueprint', 'OpenUSD / Omniverse', 'SimReady assets', 'NVIDIA NIM', 'NeMo Retriever', 'cuVS', 'PhysicsNeMo candidate', 'cuOpt candidate'],
    work: ['Interpret token/business intent', 'Select DSX baseline and constraints', 'Compare with previous AI Factories', 'Define simulation and asset needs', 'Assemble governed decision package'],
    gates: ['Prompt-to-process contract', 'Controlled context package', 'DSX baseline evidence', 'Simulation basis check', 'Deviation approval', 'Traceability matrix'],
    pills: ['DSX baseline', 'Portfolio lessons', 'Multi-simulation', 'OpenUSD assets'],
  },
  requirements: {
    label: 'Requirements & DSX Baseline',
    short: 'Requirements',
    outcomeKind: 'Baseline',
    summary: 'Transform unstructured intent or RFP into structured requirements and DSX baseline mapping.',
    intentLabel: 'Customer RFP / OPR',
    context: ['RFP / OPR', 'DSX corpus', 'customer constraints', 'approved requirement schema'],
    outcomeTitle: 'Structured DSX requirements package',
    outcome:
      'Source-bound requirements, DSX baseline mapping, missing inputs, compliance gaps and controlled deviation candidates.',
    best: 'Early customer RFP or owner requirement analysis.',
    agents: [
      { name: 'Requirement Extraction Agent', role: 'Extracts structured requirements, parameters and constraints.', input: 'RFP, OPR, specification documents.', output: 'Normalized requirements and source links.', nvidia: 'NeMo Retriever extraction + NIM LLM structured output.', evidence: 'Each requirement is tied to a source passage.' },
      { name: 'DSX Mapping Agent', role: 'Maps requirements to DSX reference baseline and rules.', input: 'Structured requirements and DSX baseline corpus.', output: 'Requirement-to-DSX compliance map.', nvidia: 'Omniverse DSX Blueprint knowledge + cuVS vector retrieval.', evidence: 'Rule references and mapped requirement IDs.' },
      { name: 'Deviation Agent', role: 'Classifies deviations, risks and approval needs.', input: 'Compliance map and unmatched requirements.', output: 'Deviation register and risk rationale.', nvidia: 'NIM LLM + DSX rule catalogue.', evidence: 'Deviation source, rule and approval path.' },
      { name: 'Clarification Agent', role: 'Asks targeted questions instead of guessing missing inputs.', input: 'Missing or ambiguous requirements.', output: 'Short clarification questions.', nvidia: 'NIM LLM with schema guardrails.', evidence: 'Question linked to missing input.' },
      { name: 'Evidence Agent', role: 'Checks every claim has a source object or document passage.', input: 'Requirements, mappings and deviations.', output: 'Validated evidence package.', nvidia: 'NeMo Retriever reranking + evidence JSON validation.', evidence: 'Evidence coverage score and unsupported-claim list.' },
    ],
    tools: ['Document parser', 'Omniverse DSX Blueprint', 'NeMo Retriever', 'cuVS vector search', 'NVIDIA NIM'],
    work: ['Extract structured requirements', 'Map requirements to DSX baseline', 'Identify missing information', 'Classify deviations', 'Prepare clarification and approval package'],
    gates: ['Source-bound extraction', 'Schema validation', 'Missing information gate', 'DSX rule mapping', 'Human baseline approval'],
    pills: ['Requirements', 'DSX mapping', 'Deviation log', 'Clarification loop'],
  },
  simulation: {
    label: 'Multi-Simulation Campaign',
    short: 'Simulation',
    outcomeKind: 'Evidence',
    summary: 'Plan and route simulations to validate a DSX-aligned AI Factory decision.',
    intentLabel: 'Engineering validation question',
    context: ['system model', 'site constraints', 'OpenUSD scene', 'SimReady metadata', 'simulation catalogue'],
    outcomeTitle: 'Simulation evidence package',
    outcome:
      'Model choices, run plan, assumptions, required inputs, expected outputs, result lineage and decision impact.',
    best: 'Engineering validation across power, cooling, controls, network and commissioning.',
    agents: [
      { name: 'Simulation Planner Agent', role: 'Chooses which simulation routes are required for the decision.', input: 'Engineering question, DSX baseline and constraints.', output: 'Simulation campaign plan.', nvidia: 'NIM LLM + simulation catalogue.', evidence: 'Simulation objective contract.' },
      { name: 'Power Simulation Agent', role: 'Frames power redundancy, RPP, UPS and ramp scenarios.', input: 'Power architecture and load assumptions.', output: 'Power validation route and expected outputs.', nvidia: 'PhysicsNeMo candidate + model/result index.', evidence: 'Model validity and input-freeze status.' },
      { name: 'Cooling / Thermal Agent', role: 'Frames liquid cooling and thermal transient checks.', input: 'Cooling architecture, CDU assumptions and workload ramp.', output: 'Thermal validation route and constraints.', nvidia: 'PhysicsNeMo candidate + OpenUSD/SimReady context.', evidence: 'Thermal model assumptions and run status.' },
      { name: 'Controls Agent', role: 'Checks CDU/BMS control logic and commissioning behavior.', input: 'Controls strategy and commissioning sequence.', output: 'Controls validation route.', nvidia: 'Simulation catalogue + NIM interpretation.', evidence: 'Control assumptions and acceptance criteria.' },
      { name: 'Network Agent', role: 'Checks topology and interconnect impact on the system decision.', input: 'Network topology and rack/pod configuration.', output: 'Network impact and simulation dependency.', nvidia: 'DSX/OpenUSD context + graph evidence.', evidence: 'Topology evidence and interconnect assumptions.' },
      { name: 'Evidence Agent', role: 'Prevents invented simulation outcomes.', input: 'All simulation plans and results.', output: 'Evidence status and gaps.', nvidia: 'NIM summarization + result lineage index.', evidence: 'No invented result gate.' },
    ],
    tools: ['PhysicsNeMo candidate', 'NVIDIA NIM', 'OpenUSD scene context', 'SimReady asset metadata', 'cuOpt candidate'],
    work: ['Define engineering decision', 'Select simulation routes', 'Freeze model inputs', 'Run or mock evidence paths', 'Interpret results and decision impact'],
    gates: ['Simulation objective contract', 'Input parameter freeze', 'Model validity check', 'No invented result gate', 'Engineer acceptance'],
    pills: ['Power', 'Cooling', 'Controls', 'Commissioning'],
  },
  openusd: {
    label: 'OpenUSD / SimReady Assets',
    short: 'OpenUSD',
    outcomeKind: 'Assets',
    summary: 'Find, request, validate and register OpenUSD/SimReady assets for AI Factory digital-twin completion.',
    intentLabel: 'Supplier asset need',
    context: ['supplier asset repository', 'OpenUSD scene', 'SimReady profile', 'interface requirements'],
    outcomeTitle: 'Validated asset integration package',
    outcome:
      'Validated OpenUSD/SimReady metadata, connection points, interface compatibility, provenance and next validation steps.',
    best: 'Supplier asset exchange and AI Factory Virtual Twin completion.',
    agents: [
      { name: 'OpenUSD Asset Agent', role: 'Finds required USD asset and scene placement needs.', input: 'Asset request and scene context.', output: 'Candidate OpenUSD assets.', nvidia: 'Omniverse DSX Blueprint + OpenUSD asset registry.', evidence: 'Asset ID, version and source.' },
      { name: 'SimReady Metadata Agent', role: 'Validates simulation-ready metadata and connection points.', input: 'Candidate asset payload.', output: 'SimReady completeness report.', nvidia: 'SimReady validation/profile rules.', evidence: 'Required metadata fields and missing items.' },
      { name: 'Supplier A2A Agent', role: 'Simulates request, permission and asset payload exchange.', input: 'Structured asset request.', output: 'Mock supplier response and permission status.', nvidia: 'Supplier repository or mock A2A endpoint.', evidence: 'Access status and asset provenance.' },
      { name: 'Interface Compatibility Agent', role: 'Checks connection and integration compatibility.', input: 'Asset, connection points and AI Factory scene.', output: 'Compatibility assessment.', nvidia: 'OpenUSD scene graph + SimReady metadata.', evidence: 'Interface checks and unresolved mismatches.' },
      { name: 'Evidence Agent', role: 'Captures provenance, version and registration status.', input: 'Asset validation outputs.', output: 'Registration evidence package.', nvidia: 'NeMo Retriever + validation schema.', evidence: 'Registration status and traceability.' },
    ],
    tools: ['Omniverse DSX Blueprint', 'OpenUSD', 'SimReady assets', 'supplier asset repository', 'NVIDIA NIM'],
    work: ['Identify required asset', 'Send structured supplier request', 'Validate format and metadata', 'Check connection points', 'Register asset in workspace'],
    gates: ['Asset request contract', 'Supplier permission check', 'Metadata completeness', 'Version/provenance check', 'Architect acceptance'],
    pills: ['OpenUSD', 'SimReady', 'Supplier A2A', 'Asset registry'],
  },
  operations: {
    label: 'Operations Exception',
    short: 'Operations',
    outcomeKind: 'Mitigation',
    summary: 'Respond to an AI Factory operations exception with DSX-aware mitigation and maintenance planning.',
    intentLabel: 'Rack anomaly / incident',
    context: ['telemetry', 'workload placement', 'maintenance plan', 'inventory / BOM', 'operating twin'],
    outcomeTitle: 'Approved mitigation plan',
    outcome:
      'Mitigation plan combining workload impact, cooling/power constraints, maintenance windows, spare-part availability and DSX operating-envelope checks.',
    best: 'Operational anomaly triage and coordinated intervention planning.',
    agents: [
      { name: 'Incident Agent', role: 'Summarizes the event and affected objects.', input: 'Alert, incident log and telemetry snapshot.', output: 'Incident contract and affected asset list.', nvidia: 'DCGM/telemetry candidate + incident log retrieval.', evidence: 'Source, timestamp and affected object mapping.' },
      { name: 'Workload Impact Agent', role: 'Assesses workload and service impact.', input: 'Affected assets and workload placement.', output: 'Workload impact and mitigation options.', nvidia: 'Run:ai candidate + workload policy data.', evidence: 'Affected workload and policy evidence.' },
      { name: 'Cooling Envelope Agent', role: 'Checks thermal/cooling constraints and safe operating window.', input: 'Thermal data, cooling assumptions and system model.', output: 'Cooling envelope assessment.', nvidia: 'Telemetry + PhysicsNeMo/simulation evidence.', evidence: 'Operating envelope check and assumptions.' },
      { name: 'Maintenance Agent', role: 'Combines planned and unplanned intervention windows.', input: 'Maintenance schedule and incident severity.', output: 'Candidate intervention window.', nvidia: 'cuOpt candidate for scheduling optimization.', evidence: 'Schedule constraints and optimization objective.' },
      { name: 'Spare Parts Agent', role: 'Checks replacement, stock and lead-time risk.', input: 'BOM, inventory and replacement rules.', output: 'Spare availability and procurement risk.', nvidia: 'Inventory/BOM data + NIM summarization.', evidence: 'Stock source and lead-time assumptions.' },
      { name: 'Evidence Agent', role: 'Builds the approval-ready mitigation package.', input: 'All operational analyses.', output: 'Traceable mitigation package.', nvidia: 'NIM report generation.', evidence: 'Before/after lineage and human approval gate.' },
    ],
    tools: ['DCGM candidate', 'Run:ai candidate', 'NVIDIA NIM', 'cuOpt candidate', 'OpenUSD operating twin'],
    work: ['Classify incident', 'Map affected assets', 'Analyze workload/cooling impact', 'Optimize maintenance and spare availability', 'Request approval for mitigation'],
    gates: ['Incident source validation', 'Affected-object mapping', 'Operating envelope check', 'Stock evidence', 'Human approval'],
    pills: ['Incident', 'Workload', 'Maintenance', 'Spare parts'],
  },
  interconnect: {
    label: 'Interconnect Readiness',
    short: 'Interconnect',
    outcomeKind: 'Readiness',
    summary: 'Validate logical-to-physical interconnect readiness for a DSX-based AI Factory configuration.',
    intentLabel: 'Rack / pod interconnect check',
    context: ['logical topology', 'OpenUSD scene', 'SimReady connection points', 'BOM / catalogue', 'OCP / DSX rules'],
    outcomeTitle: 'Interconnect readiness report',
    outcome:
      'Readiness report listing physical routing issues, cable risks, BOM/lead-time concerns, deviations and recommended corrections.',
    best: 'Buildability, P2P routing and supply readiness before implementation.',
    agents: [
      { name: 'Interconnect Agent', role: 'Maps logical links to physical routes.', input: 'Logical topology and scene context.', output: 'Logical-to-physical link map.', nvidia: 'OpenUSD scene/context + P2P topology data.', evidence: 'Object-level route references.' },
      { name: 'Cabling Rules Agent', role: 'Checks cable length, bend radius and pathway constraints.', input: 'Routes, cable classes and rules corpus.', output: 'Rule violations and corrective options.', nvidia: 'Rules corpus via NeMo Retriever.', evidence: 'Rule citation for each exception.' },
      { name: 'BOM / Lead-Time Agent', role: 'Checks availability, alternatives and schedule risk.', input: 'BOM, catalogue and supplier data.', output: 'Lead-time and substitute risk report.', nvidia: 'BOM/catalogue + cuVS vector search.', evidence: 'Catalogue source and lead-time assumption.' },
      { name: 'DSX Rules Agent', role: 'Checks if connectivity remains DSX-compliant.', input: 'Interconnect map and DSX baseline.', output: 'DSX compliance and deviation status.', nvidia: 'DSX Blueprint/rules + NIM classification.', evidence: 'Compliance map and deviation rationale.' },
      { name: 'Evidence Agent', role: 'Creates traceable exception report.', input: 'All interconnect checks.', output: 'Readiness package.', nvidia: 'Evidence schema + reranking.', evidence: 'Traceability matrix and unresolved risks.' },
    ],
    tools: ['OpenUSD scene context', 'SimReady connection-point metadata', 'NeMo Retriever', 'cuVS vector search', 'NVIDIA NIM'],
    work: ['Map logical links to physical routes', 'Check bend radius and routing rules', 'Check cable catalogue and lead times', 'Classify DSX deviations', 'Package readiness evidence'],
    gates: ['Object traceability', 'Rule citation', 'BOM evidence', 'No silent pruning', 'Engineer review'],
    pills: ['P2P', 'Cable length', 'Bend radius', 'Lead time'],
  },
  robot: {
    label: 'Humanoid Robot Twin',
    short: 'Robot Twin',
    outcomeKind: 'Service',
    summary: 'Diagnose a humanoid robot issue and prepare a safe evidence-backed maintenance intervention.',
    intentLabel: 'Robot anomaly / service issue',
    context: ['telemetry / logs', 'robot asset context', 'service procedures', 'parts catalogue', 'safety rules'],
    outcomeTitle: 'Robot service work package',
    outcome:
      'Maintenance package with suspected subsystem, approved procedure, replacement parts, simulation checks and technician approval gates.',
    best: 'Humanoid robot field-service assistant pattern.',
    agents: [
      { name: 'Robot Diagnostic Agent', role: 'Classifies symptom and suspected subsystem.', input: 'Fault note, logs and telemetry.', output: 'Diagnosis hypothesis and affected subsystem.', nvidia: 'NIM robot/domain LLM + telemetry retrieval.', evidence: 'Symptom-to-subsystem trace.' },
      { name: 'Procedure Agent', role: 'Retrieves approved maintenance instructions.', input: 'Diagnosis and asset configuration.', output: 'Approved procedure package.', nvidia: 'NeMo Retriever over service procedures.', evidence: 'Procedure source and revision.' },
      { name: 'Parts Agent', role: 'Checks replacement parts and compatibility.', input: 'Configuration and suspected part.', output: 'Compatible replacement options.', nvidia: 'Inventory/configuration data.', evidence: 'Compatibility and stock source.' },
      { name: 'Safety Gate Agent', role: 'Blocks unsafe autonomous actions.', input: 'Procedure and planned action.', output: 'Safety approval requirement.', nvidia: 'Safety rules + schema validation.', evidence: 'Safety-critical boundary status.' },
      { name: 'Simulation Agent', role: 'Selects thermal/actuator checks when needed.', input: 'Diagnosis and robot digital context.', output: 'Simulation check recommendation.', nvidia: 'PhysicsNeMo candidate + OpenUSD/SimReady robot context.', evidence: 'Model need and assumptions.' },
      { name: 'Evidence Agent', role: 'Packages technician-ready intervention evidence.', input: 'All service analyses.', output: 'Robot service work package.', nvidia: 'NIM report generation.', evidence: 'Evidence lineage and technician sign-off.' },
    ],
    tools: ['NIM robot/domain LLM', 'OpenUSD robot asset context', 'SimReady metadata', 'PhysicsNeMo candidate', 'synthetic data candidate'],
    work: ['Classify symptom', 'Retrieve approved procedure', 'Check safety boundary', 'Validate parts and configuration', 'Prepare technician work package'],
    gates: ['Safety-critical boundary', 'Approved procedure source', 'Technician approval', 'Part compatibility', 'Evidence lineage'],
    pills: ['Diagnosis', 'Procedure', 'Safety', 'Service'],
  },
};

export const EXAMPLE_INTENTS = [
  'We need to deploy a 250MW AI Factory in southern Europe. Preserve DSX compliance, minimize water usage, support future Rubin expansion, compare with previous AI Factories, and propose the required simulations and evidence package.',
  'Transform this customer RFP into a DSX-aligned baseline, identify missing information, and prepare a requirements package.',
  'Plan a multi-simulation campaign for a DSX AI Factory variant: power redundancy, cooling transient response, controls and commissioning.',
  'Find the right OpenUSD and SimReady supplier assets to complete the AI Factory digital twin and validate interfaces.',
  'Check whether the rack and pod configuration is interconnect-ready: P2P links, cable routing, bend radius, BOM and lead-time risk.',
  'Rack 12 shows an abnormal thermal pattern. Combine workload impact, cooling envelope, maintenance planning and spare availability into a safe mitigation plan.',
  'A humanoid robot shows repeated actuator overheating. Diagnose the likely subsystem, retrieve the approved procedure and prepare a safe intervention plan.',
];

export function detectPattern(intent) {
  const text = intent.toLowerCase();
  if (/robot|humanoid|actuator|procedure|service/.test(text)) return 'robot';
  if (/interconnect|cable|routing|bend radius|p2p|lead-time|bom/.test(text)) return 'interconnect';
  if (/openusd|simready|asset|supplier|omniverse|metadata/.test(text)) return 'openusd';
  if (/simulation|power redundancy|cooling transient|commissioning|controls|cdu|rpp/.test(text)) return 'simulation';
  if (/incident|thermal pattern|maintenance|spare|mitigation|anomaly|rack 12/.test(text)) return 'operations';
  if (/rfp|requirement|baseline|missing information|compliance|opr/.test(text)) return 'requirements';
  return 'token';
}
